In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
db_url = 'postgresql://forecast_user:forecast_pass@localhost:5432/forecast_db'

In [5]:
engine = create_engine(db_url)

In [7]:
cities_df = pd.read_sql_query('SELECT * FROM cities', con=engine)

In [8]:
from IPython.display import display
display(cities_df)

   id         name  lat_coord  lon_coord country
0   1       Kazan’    55.7887    49.1221      RU
1   2       Moscow    55.7522    37.6156      RU
2   3  Makhachkala    42.9764    47.5024      RU

In [9]:
wi_df = pd.read_sql_query('SELECT * FROM weather_info LIMIT 40', con=engine)

In [10]:
display(wi_df)

,id,city_api_id,dt,dt_txt,temp,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,wind_speed,wind_degree
0,1,551487,1597503600,2020-08-15 15:00:00,14.108889,14.039444,14.108889,1006.0,1007.0,997.0,88,6.06,14.0
1,2,551487,1597514400,2020-08-15 18:00:00,14.057222,14.024444,14.057222,1007.0,1008.0,998.0,90,5.49,8.0
2,3,551487,1597525200,2020-08-15 21:00:00,14.026111,14.016111,14.026111,1007.0,1007.0,997.0,90,5.26,6.0
3,4,551487,1597536000,2020-08-16 00:00:00,13.996111,13.994444,13.996111,1007.0,1007.0,997.0,89,5.44,6.0
4,5,551487,1597546800,2020-08-16 03:00:00,13.976667,13.976667,13.976667,1007.0,1007.0,997.0,88,5.06,5.0
5,6,551487,1597557600,2020-08-16 06:00:00,14.033889,14.033889,14.033889,1008.0,1008.0,998.0,84,4.89,355.0
6,7,551487,1597568400,2020-08-16 09:00:00,14.265556,14.265556,14.265556,1008.0,1008.0,998.0,70,5.06,1.0
7,8,551487,1597579200,2020-08-16 12:00:00,14.332222,14.332222,14.332222,1008.0,1008.0,998.0,63,4.66,357.0
8,9,551487,1597590000,2020-08-16 15:00:00,14.280000,14.280000,14.280000,1007.0,1007.0,998.0,69,3.02,337.0
9,10,551487,1597600800,2020-08-16 18:00:00,14.070556,14.070556,14.070556,1008.0,1008.0,998.0,80,2.58,330.0
10,11,551487,1597611600,2020-08-16 21:00:00,14.013333,14.013333,14.013333,1007.0,1007.0,997.0,84,2.13,304.0
11,12,551487,1597622400,2020-08-17 00:00:00,13.979444,13.979444,13.979444,1006.0,1006.0,996.0,88,2.33,283.0
12,13,551487,1597633200,2020-08-17 03:00:00,14.029444,14.029444,14.029444,1004.0,1004.0,995.0,81,2.48,260.0
13,14,551487,1597644000,2020-08-17 06:00:00,14.031667,14.031667,14.031667,1003.0,1003.0,993.0,87,3.59,196.0
14,15,551487,1597654800,2020-08-17 09:00:00,14.132778,14.132778,14.132778,1002.0,1002.0,992.0,93,2.75,240.0
15,16,551487,1597665600,2020-08-17 12:00:00,14.306667,14.306667,14.306667,1002.0,1002.0,992.0,83,3.49,323.0
16,17,551487,1597676400,2020-08-17 15:00:00,14.232222,14.232222,14.232222,1003.0,1003.0,993.0,81,5.95,344.0
17,18,551487,1597687200,2020-08-17 18:00:00,13.997222,13.997222,13.997222,1004.0,1004.0,994.0,81,3.91,341.0
18,19,551487,1597698000,2020-08-17 21:00:00,13.926111,13.926111,13.926111,1005.0,1005.0,995.0,78,4.38,321.0
19,20,551487,1597708800,2020-08-18 00:00:00,13.842222,13.842222,13.842222,1006.0,1006.0,996.0,81,4.19,316.0
20,21,551487,1597719600,2020-08-18 03:00:00,13.885556,13.885556,13.885556,1007.0,1007.0,997.0,80,4.93,316.0
21,22,551487,1597730400,2020-08-18 06:00:00,14.161111,14.161111,14.161111,1008.0,1008.0,998.0,63,6.23,326.0
22,23,551487,1597741200,2020-08-18 09:00:00,14.321111,14.321111,14.321111,1008.0,1008.0,998.0,51,6.35,329.0
23,24,551487,1597752000,2020-08-18 12:00:00,14.327778,14.327778,14.327778,1008.0,1008.0,998.0,53,5.86,322.0
24,25,551487,1597762800,2020-08-18 15:00:00,14.214444,14.214444,14.214444,1009.0,1009.0,999.0,63,3.72,319.0
25,26,551487,1597773600,2020-08-18 18:00:00,14.028889,14.028889,14.028889,1010.0,1010.0,1000.0,71,3.18,297.0
26,27,551487,1597784400,2020-08-18 21:00:00,13.947222,13.947222,13.947222,1011.0,1011.0,1001.0,77,2.96,301.0
27,28,551487,1597795200,2020-08-19 00:00:00,13.881111,13.881111,13.881111,1011.0,1011.0,1002.0,83,2.53,301.0
28,29,551487,1597806000,2020-08-19 03:00:00,13.942778,13.942778,13.942778,1012.0,1012.0,1002.0,82,2.04,315.0
29,30,551487,1597816800,2020-08-19 06:00:00,14.225556,14.225556,14.225556,1012.0,1012.0,1003.0,62,2.51,322.0
30,31,551487,1597827600,2020-08-19 09:00:00,14.386667,14.386667,14.386667,1013.0,1013.0,1003.0,51,2.87,316.0
31,32,551487,1597838400,2020-08-19 12:00:00,14.375000,14.375000,14.375000,1012.0,1012.0,1003.0,56,2.57,297.0
32,33,551487,1597849200,2020-08-19 15:00:00,14.299444,14.299444,14.299444,1013.0,1013.0,1003.0,62,1.42,286.0
33,34,551487,1597860000,2020-08-19 18:00:00,14.090000,14.090000,14.090000,1014.0,1014.0,1004.0,70,0.42,271.0
34,35,551487,1597870800,2020-08-19 21:00:00,14.021111,14.021111,14.021111,1014.0,1014.0,1004.0,77,0.89,214.0
35,36,551487,1597881600,2020-08-20 00:00:00,13.985000,13.985000,13.985000,1014.0,1014.0,1005.0,81,1.36,234.0
36,37,551487,1597892400,2020-08-20 03:00:00,14.084444,14.084444,14.084444,1015.0,1015.0,1005.0,77,0.88,266.0
37,38,551487,1597903200,2020-08-20 06:00:00,14.187778,14.187778,14.187778,1015.0,1015.0,1005.0,71,0.17,258.0
38,39,551487,1597914000,2020-08-20 09:00:00,14.475556,14.475556,14.475556,1015.0,1015.0,1005.0,54,1.80,225.0
39,40,551487,1597924800,2020-08-20 12:00:00,14.570000,14.570000,14.570000,1014.0,1014.0,1005.0,50,1.52,218.0

In [11]:
display(wi_df[wi_df['wind_speed'] > 5])

,id,city_api_id,dt,dt_txt,temp,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,wind_speed,wind_degree
0,1,551487,1597503600,2020-08-15 15:00:00,14.108889,14.039444,14.108889,1006.0,1007.0,997.0,88,6.06,14.0
1,2,551487,1597514400,2020-08-15 18:00:00,14.057222,14.024444,14.057222,1007.0,1008.0,998.0,90,5.49,8.0
2,3,551487,1597525200,2020-08-15 21:00:00,14.026111,14.016111,14.026111,1007.0,1007.0,997.0,90,5.26,6.0
3,4,551487,1597536000,2020-08-16 00:00:00,13.996111,13.994444,13.996111,1007.0,1007.0,997.0,89,5.44,6.0
4,5,551487,1597546800,2020-08-16 03:00:00,13.976667,13.976667,13.976667,1007.0,1007.0,997.0,88,5.06,5.0
6,7,551487,1597568400,2020-08-16 09:00:00,14.265556,14.265556,14.265556,1008.0,1008.0,998.0,70,5.06,1.0
16,17,551487,1597676400,2020-08-17 15:00:00,14.232222,14.232222,14.232222,1003.0,1003.0,993.0,81,5.95,344.0
21,22,551487,1597730400,2020-08-18 06:00:00,14.161111,14.161111,14.161111,1008.0,1008.0,998.0,63,6.23,326.0
22,23,551487,1597741200,2020-08-18 09:00:00,14.321111,14.321111,14.321111,1008.0,1008.0,998.0,51,6.35,329.0
23,24,551487,1597752000,2020-08-18 12:00:00,14.327778,14.327778,14.327778,1008.0,1008.0,998.0,53,5.86,322.0

In [12]:
display(wi_df[wi_df['wind_speed'] < 5])

,id,city_api_id,dt,dt_txt,temp,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,wind_speed,wind_degree
5,6,551487,1597557600,2020-08-16 06:00:00,14.033889,14.033889,14.033889,1008.0,1008.0,998.0,84,4.89,355.0
7,8,551487,1597579200,2020-08-16 12:00:00,14.332222,14.332222,14.332222,1008.0,1008.0,998.0,63,4.66,357.0
8,9,551487,1597590000,2020-08-16 15:00:00,14.280000,14.280000,14.280000,1007.0,1007.0,998.0,69,3.02,337.0
9,10,551487,1597600800,2020-08-16 18:00:00,14.070556,14.070556,14.070556,1008.0,1008.0,998.0,80,2.58,330.0
10,11,551487,1597611600,2020-08-16 21:00:00,14.013333,14.013333,14.013333,1007.0,1007.0,997.0,84,2.13,304.0
11,12,551487,1597622400,2020-08-17 00:00:00,13.979444,13.979444,13.979444,1006.0,1006.0,996.0,88,2.33,283.0
12,13,551487,1597633200,2020-08-17 03:00:00,14.029444,14.029444,14.029444,1004.0,1004.0,995.0,81,2.48,260.0
13,14,551487,1597644000,2020-08-17 06:00:00,14.031667,14.031667,14.031667,1003.0,1003.0,993.0,87,3.59,196.0
14,15,551487,1597654800,2020-08-17 09:00:00,14.132778,14.132778,14.132778,1002.0,1002.0,992.0,93,2.75,240.0
15,16,551487,1597665600,2020-08-17 12:00:00,14.306667,14.306667,14.306667,1002.0,1002.0,992.0,83,3.49,323.0
17,18,551487,1597687200,2020-08-17 18:00:00,13.997222,13.997222,13.997222,1004.0,1004.0,994.0,81,3.91,341.0
18,19,551487,1597698000,2020-08-17 21:00:00,13.926111,13.926111,13.926111,1005.0,1005.0,995.0,78,4.38,321.0
19,20,551487,1597708800,2020-08-18 00:00:00,13.842222,13.842222,13.842222,1006.0,1006.0,996.0,81,4.19,316.0
20,21,551487,1597719600,2020-08-18 03:00:00,13.885556,13.885556,13.885556,1007.0,1007.0,997.0,80,4.93,316.0
24,25,551487,1597762800,2020-08-18 15:00:00,14.214444,14.214444,14.214444,1009.0,1009.0,999.0,63,3.72,319.0
25,26,551487,1597773600,2020-08-18 18:00:00,14.028889,14.028889,14.028889,1010.0,1010.0,1000.0,71,3.18,297.0
26,27,551487,1597784400,2020-08-18 21:00:00,13.947222,13.947222,13.947222,1011.0,1011.0,1001.0,77,2.96,301.0
27,28,551487,1597795200,2020-08-19 00:00:00,13.881111,13.881111,13.881111,1011.0,1011.0,1002.0,83,2.53,301.0
28,29,551487,1597806000,2020-08-19 03:00:00,13.942778,13.942778,13.942778,1012.0,1012.0,1002.0,82,2.04,315.0
29,30,551487,1597816800,2020-08-19 06:00:00,14.225556,14.225556,14.225556,1012.0,1012.0,1003.0,62,2.51,322.0
30,31,551487,1597827600,2020-08-19 09:00:00,14.386667,14.386667,14.386667,1013.0,1013.0,1003.0,51,2.87,316.0
31,32,551487,1597838400,2020-08-19 12:00:00,14.375000,14.375000,14.375000,1012.0,1012.0,1003.0,56,2.57,297.0
32,33,551487,1597849200,2020-08-19 15:00:00,14.299444,14.299444,14.299444,1013.0,1013.0,1003.0,62,1.42,286.0
33,34,551487,1597860000,2020-08-19 18:00:00,14.090000,14.090000,14.090000,1014.0,1014.0,1004.0,70,0.42,271.0
34,35,551487,1597870800,2020-08-19 21:00:00,14.021111,14.021111,14.021111,1014.0,1014.0,1004.0,77,0.89,214.0
35,36,551487,1597881600,2020-08-20 00:00:00,13.985000,13.985000,13.985000,1014.0,1014.0,1005.0,81,1.36,234.0
36,37,551487,1597892400,2020-08-20 03:00:00,14.084444,14.084444,14.084444,1015.0,1015.0,1005.0,77,0.88,266.0
37,38,551487,1597903200,2020-08-20 06:00:00,14.187778,14.187778,14.187778,1015.0,1015.0,1005.0,71,0.17,258.0
38,39,551487,1597914000,2020-08-20 09:00:00,14.475556,14.475556,14.475556,1015.0,1015.0,1005.0,54,1.80,225.0
39,40,551487,1597924800,2020-08-20 12:00:00,14.570000,14.570000,14.570000,1014.0,1014.0,1005.0,50,1.52,218.0

In [13]:
wi_df_full = pd.read_sql_query('SELECT * FROM weather_info', con=engine)

In [14]:
wi_df_full.shape

(120, 13)

In [16]:
wind_ids = wi_df_full.groupby(['city_api_id'])['wind_degree'].transform(max) == wi_df_full['wind_degree']

In [17]:
wi_df_full[wind_ids]

,id,city_api_id,dt,dt_txt,temp,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,wind_speed,wind_degree
7,8,551487,1597579200,2020-08-16 12:00:00,14.332222,14.332222,14.332222,1008.0,1008.0,998.0,63,4.66,357.0
57,58,524901,1597687200,2020-08-17 18:00:00,14.484444,14.484444,14.484444,1010.0,1010.0,994.0,67,2.14,351.0
84,85,532096,1597546800,2020-08-16 03:00:00,14.542222,14.542222,14.542222,1013.0,1013.0,1013.0,52,2.98,297.0